const PROFESSION_KEYWORDS = {
  farmer: ["farmer", "agriculture", "kisan", "cultivator", "kheti", "krishi"],
  student: [
    "student",
    "school",
    "college",
    "vidyarthi",
    "padhaku",
    "exam",
    "upsc",
    "neet",
    "jee",
    "coaching",
  ],
  worker: [
    "worker",
    "labour",
    "labor",
    "daily wage",
    "majdoor",
    "mazdoor",
    "majduar",
    "kuli",
    "coolie",
    "construction",
    "factory",
    "beedi worker",
    "rickshaw",
    "auto driver",
    "driver",
    "domestic worker",
    "safai karamchari",
  ],
  entrepreneur: [
    "business",
    "entrepreneur",
    "startup",
    "self employed",
    "self-employed",
    "shop",
    "store",
    "medical shop",
    "medicine shop",
    "pharmacy",
    "dukan",
    "dukandar",
    "trader",
    "kirana",
    "silai",
    "tailor",
    "darzi",
    "artisan",
    "craftsman",
    "housewife",
    "homemaker",
    "ghar grihasti",
    "widow",
    "vidhwa",
    "single woman",
    "micro business",
    "small business",
    "msme",
  ],
};

const CATEGORY_KEYWORDS = {
  sc: ["sc", "scheduled caste", "dalit"],
  st: ["st", "scheduled tribe", "tribal", "adivasi", "janjati"],
  obc: [
    "obc",
    "backward class",
    "other backward class",
    "bc",
    "obc-ncl",
    "obc ncl",
    "ncl",
    "vj",
    "nt",
    "sbc",
    "vj/nt",
    "vj nt",
    "sebc",
    "other backward",
  ],
  ews: ["ews", "economically weaker", "general ews", "gen-ews"],
  minority: ["minority", "religious minority", "muslim", "christian", "sikh"],
  general: ["general category", "open category", "general", "unreserved", "open", "apl"],
  // Special / overlapping
  pwd: ["divyang", "pwd", "disabled", "differently abled", "viklang", "handicap"],
  bpl: ["bpl", "below poverty line", "antodaya"],
};

module.exports = {
  PROFESSION_KEYWORDS,
  CATEGORY_KEYWORDS,
};
